source 'https://gitee.com/mirrors/CocoaPods-Specs.git'
#source 'https://github.com/CocoaPods/Specs.git'
  
platform :ios ,'13.0'
use_frameworks!

post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
  end
end

# 共通的库
def common_pods
  pod 'WCDB.swift', '~> 2.1.5'
end

target 'WCDBDemo' do
  common_pods
  #pod 'WCDB.swift', '~> 1.0.8.2'  #2.1.5
end

#target 'HTKeyboard' do
#  common_pods
#end
