#source 'https://github.com/CocoaPods/Specs.git'
  
platform :ios ,'14.0'
use_frameworks!

target 'MyCloudDrive' do
  
  pod 'SnapKit'
  pod 'SwiftyDropbox'
  pod 'GoogleSignIn'
  pod 'GoogleAPIClientForREST/Drive'
  pod 'MSAL', '~> 1.5.1'
  pod 'MSGraphClientSDK'
  pod 'MSGraphClientModels'
end
